# Generated by Django 5.0.4 on 2024-05-24 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_customuser_is_superuser_subscription'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_superuser',
        ),
    ]
